name: Unpublish Pull Request NPM tag

on:
  pull_request_target:
    types:
      - closed

jobs:
  unpublish-pr:
    name: "Unpublish Pull Request NPM tag"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Ensure NPM access
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Get package versions for PR tag
        id: pr_versions
        run: |
          source /home/runner/.bashrc
          PACKAGES=$(pnpm list -r --depth=-1 | awk '{ if($0 !~ /^[[:space:]]*$/) print $1}' | sed 's/@[0-9\.]*$//')
          PACKAGE_VERSION=""
          for PACKAGE in $PACKAGES
          do
              if $(npm view $PACKAGE &> >(grep -q "npm ERR! code E404")); then
                  VERSIONS=$(npm view $PACKAGE --json)
                  PR_VERSIONS=$(echo "$VERSIONS" | tr ',' '\n' | tr -d '[]"' | grep -F "pr-${{ github.event.pull_request.number }}" | xargs)
                  if [ ! -z "$PR_VERSIONS" ]; then
                      PACKAGE_VERSIONS="${PACKAGE_VERSIONS} ${PR_VERSIONS}"
                  fi
              fi
          done 
          echo "::set-output name=packages::$PACKAGE@$PACKAGE_VERSIONS"

      - name: Unpublish NPM PR Tag Versions
        run: |
          for PACKAGE in ${{ steps.pr_versions.outputs.packages }}
          do
            echo "Unpublishing ${PACKAGE}"
            npm --force unpublish ${PACKAGE}
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
