name: "Unpublish old versions"

on:
  workflow_dispatch:
    inputs:
      delete_packages:
        type: boolean
        description: Delete packages? otherwise dry-run mode will be used
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-npm-versions:
    name: Unpublish versions next and pr
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node@master
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - run: |
          node ./scripts/release-unpublish.js
        env:
          DELETE_PACKAGES: ${{ github.event.inputs.delete_packages}}
